version: '3.3'

volumes:
  pg_data:
  static:
  media:
  redoc:
  
services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/app/media
